#pragma once
#include "BodyStateEnums.generated.h"

UENUM(BlueprintType)
enum BodyStateHandType
{
	BodyState_HAND_UNKNOWN,
	BodyState_HAND_LEFT,
	BodyState_HAND_RIGHT
};


//Standard UE skeleton - Good Baseline for now
UENUM(BlueprintType)
enum BodyStateUEHumanoidBone
{
	
	BONE_ROOT,
	
	//Body
	BONE_PELVIS,
	BONE_SPINE_01,
	BONE_SPINE_02,
	BONE_SPINE_03,

	//Left Arm
	BONE_CLAVICLE_L,
	BONE_UPPERARM_L,
	BONE_LOWERARM_L,
	BONE_HAND_L,
	BONE_INDEX_01_L,
	BONE_INDEX_02_L,
	BONE_INDEX_03_L,
	BONE_MIDDLE_01_L,
	BONE_MIDDLE_02_L,
	BONE_MIDDLE_03_L,
	BONE_PINKY_01_L,
	BONE_PINKY_02_L,
	BONE_PINKY_03_L,
	BONE_RING_01_L,
	BONE_RING_02_L,
	BONE_RING_03_L,
	BONE_THUMB_01_L,
	BONE_THUMB_02_L,
	BONE_THUMB_03_L,
	BONE_LOWERARM_TWIST_01_L,
	BONE_UPPERARM_TWIST_01_L,

	//Right Arm
	BONE_CLAVICLE_R,
	BONE_UPPERARM_R,
	BONE_LOWERARM_R,
	BONE_HAND_R,
	BONE_INDEX_01_R,
	BONE_INDEX_02_R,
	BONE_INDEX_03_R,
	BONE_MIDDLE_01_R,
	BONE_MIDDLE_02_R,
	BONE_MIDDLE_03_R,
	BONE_PINKY_01_R,
	BONE_PINKY_02_R,
	BONE_PINKY_03_R,
	BONE_RING_01_R,
	BONE_RING_02_R,
	BONE_RING_03_R,
	BONE_THUMB_01_R,
	BONE_THUMB_02_R,
	BONE_THUMB_03_R,
	BONE_LOWERARM_TWIST_01_R,
	BONE_UPPERARM_TWIST_01_R,

	//Head
	BONE_NECK_01,
	BONE_HEAD,

	//Left Foot
	BONE_THIGH_L,
	BONE_CALF_L,
	BONE_CALF_TWIST_01_L,
	BONE_FOOT_L,
	BONE_BALL_L,
	BONE_THIGH_TWIST_01_L,

	//Right Foot
	BONE_THIGH_R,
	BONE_CALF_R,
	BONE_CALF_TWIST_01_R,
	BONE_FOOT_R,
	BONE_BALL_R,
	BONE_THIGH_TWIST_01_R

	//IK types ignored
};